#pragma once

#include <cstdint>
#include <string_view>

namespace localization
{
    constexpr std::uint64_t fnv1a( std::string_view s ) noexcept
    {
        std::uint64_t h{ 14695981039346656037ull };
        for ( const auto c : s )
        {
            h ^= static_cast<unsigned char>( c );
            h *= 1099511628211ull;
        }
        return h;
    }

    [[nodiscard]] inline std::string_view tr( std::string_view s ) noexcept
    {
        switch ( fnv1a( s ) )
        {
#define ZH(en, zh) case fnv1a(en): if ( s == en ) return zh; break
            ZH( "ragebot", "暴力瞄準" );
            ZH( "legitbot", "合法瞄準" );
            ZH( "player", "玩家" );
            ZH( "world", "世界" );
            ZH( "skins", "造型" );
            ZH( "misc", "其他" );
            ZH( "config", "設定" );
            ZH( "general", "一般" );
            ZH( "pistol", "手槍" );
            ZH( "smg", "衝鋒槍" );
            ZH( "rifle", "步槍" );
            ZH( "shotgun", "霰彈槍" );
            ZH( "sniper", "狙擊槍" );
            ZH( "lmg", "輕機槍" );
            ZH( "enemies", "敵人" );
            ZH( "allies", "隊友" );
            ZH( "local", "本地玩家" );
            ZH( "esp", "透視" );
            ZH( "scene", "場景" );
            ZH( "weather", "天氣" );
            ZH( "guns", "槍械" );
            ZH( "knives", "刀具" );
            ZH( "gloves", "手套" );
            ZH( "agents", "探員" );
            ZH( "main", "主要" );
            ZH( "removals", "移除效果" );
            ZH( "camera", "鏡頭" );
            ZH( "hud", "介面" );

            ZH( "enabled", "啟用" );
            ZH( "enable", "啟用" );
            ZH( "disabled", "停用" );
            ZH( "silent", "靜默瞄準" );
            ZH( "no spread", "無散布" );
            ZH( "double tap", "雙發" );
            ZH( "force shot in air", "空中強制射擊" );
            ZH( "force shot on ground", "地面強制射擊" );
            ZH( "extrapolation", "外推預測" );
            ZH( "max extrapolate", "最大外推" );
            ZH( "max fov", "最大視野角" );
            ZH( "fov", "視野角" );
            ZH( "hit chance", "命中率" );
            ZH( "hitchance", "命中率" );
            ZH( "min damage", "最低傷害" );
            ZH( "hit chance override", "覆寫命中率" );
            ZH( "min damage override", "覆寫最低傷害" );
            ZH( "value", "數值" );
            ZH( "force b-aim", "強制身體瞄準" );
            ZH( "dynamic point scale", "動態點位縮放" );
            ZH( "debug multipoints", "顯示多點除錯" );
            ZH( "point scale", "點位縮放" );
            ZH( "hitboxes", "命中部位" );
            ZH( "head", "頭部" );
            ZH( "chest", "胸部" );
            ZH( "stomach", "腹部" );
            ZH( "arms", "手臂" );
            ZH( "legs", "腿部" );
            ZH( "paws", "腳部" );
            ZH( "anti aim", "反瞄準" );
            ZH( "pitch", "俯仰" );
            ZH( "none", "無" );
            ZH( "down", "向下" );
            ZH( "up", "向上" );
            ZH( "compensate roll", "補償翻滾角" );
            ZH( "force left", "強制向左" );
            ZH( "force right", "強制向右" );
            ZH( "hide onshot", "射擊時隱藏" );
            ZH( "avoid backstab", "避免背刺" );
            ZH( "direction indicator", "方向指示器" );
            ZH( "color", "顏色" );
            ZH( "glow", "發光" );
            ZH( "glow strength", "發光強度" );
            ZH( "auto revolver", "自動左輪" );
            ZH( "zeusbot", "電擊槍自瞄" );
            ZH( "drop after", "使用後丟棄" );
            ZH( "knifebot", "小刀自動攻擊" );
            ZH( "quick peek", "快速探頭" );
            ZH( "base color", "基礎顏色" );
            ZH( "retracting color", "返回顏色" );
            ZH( "duck peek", "蹲伏探頭" );

            ZH( "aimbot", "自動瞄準" );
            ZH( "smooth", "平滑度" );
            ZH( "visualize fov", "顯示視野範圍" );
            ZH( "recoil control", "後座力控制" );
            ZH( "standalone rcs", "獨立壓槍" );
            ZH( "strength", "強度" );
            ZH( "min", "最小" );
            ZH( "max", "最大" );
            ZH( "triggerbot", "自動扳機" );
            ZH( "delay", "延遲" );
            ZH( "head only", "僅頭部" );
            ZH( "seeded", "固定隨機種子" );
            ZH( "autowall", "穿牆判定" );

            ZH( "esp overlay", "玩家透視" );
            ZH( "bounding box", "外框" );
            ZH( "style", "樣式" );
            ZH( "full", "完整" );
            ZH( "cornered", "角框" );
            ZH( "fill", "填充" );
            ZH( "outline", "外框線" );
            ZH( "corner length", "角框長度" );
            ZH( "visible color", "可見顏色" );
            ZH( "occluded color", "遮擋顏色" );
            ZH( "skeleton", "骨骼" );
            ZH( "mode", "模式" );
            ZH( "normal", "一般" );
            ZH( "backtrack", "回溯" );
            ZH( "thickness", "粗細" );
            ZH( "health bar", "生命條" );
            ZH( "ammo bar", "彈藥條" );
            ZH( "position", "位置" );
            ZH( "left", "左側" );
            ZH( "top", "上方" );
            ZH( "bottom", "下方" );
            ZH( "gradient", "漸層" );
            ZH( "show value", "顯示數值" );
            ZH( "full color", "滿值顏色" );
            ZH( "low color", "低值顏色" );
            ZH( "background", "背景" );
            ZH( "outline color", "外框顏色" );
            ZH( "text color", "文字顏色" );
            ZH( "glow color", "發光顏色" );
            ZH( "name", "名稱" );
            ZH( "weapon", "武器" );
            ZH( "display", "顯示方式" );
            ZH( "text", "文字" );
            ZH( "icon", "圖示" );
            ZH( "text + icon", "文字 + 圖示" );
            ZH( "icon color", "圖示顏色" );
            ZH( "info flags", "資訊標記" );
            ZH( "flags", "標記" );
            ZH( "money", "金錢" );
            ZH( "armor", "護甲" );
            ZH( "kit", "拆彈器" );
            ZH( "scoped", "開鏡" );
            ZH( "defusing", "拆彈中" );
            ZH( "flashed", "致盲" );
            ZH( "ping", "延遲" );
            ZH( "distance", "距離" );
            ZH( "oof arrows", "螢幕外箭頭" );
            ZH( "width", "寬度" );
            ZH( "height", "高度" );
            ZH( "radius x", "水平半徑" );
            ZH( "radius y", "垂直半徑" );
            ZH( "ragdoll glow", "屍體發光" );
            ZH( "chams", "材質透視" );
            ZH( "ragdoll chams", "屍體材質透視" );
            ZH( "material", "材質" );
            ZH( "primary layer", "主要圖層" );
            ZH( "secondary layer", "次要圖層" );
            ZH( "overlay layer", "覆蓋圖層" );
            ZH( "lower opacity", "降低透明度" );
            ZH( "opacity", "透明度" );
            ZH( "only when scoped", "僅開鏡時" );
            ZH( "liquid", "液體" );
            ZH( "metallic", "金屬" );
            ZH( "matte", "霧面" );
            ZH( "flat", "平面" );
            ZH( "bloom", "泛光" );
            ZH( "outlines", "輪廓" );
            ZH( "electric", "電流" );
            ZH( "distortion", "扭曲" );
            ZH( "hologram", "全息" );
            ZH( "pearl", "珍珠" );

            ZH( "group", "群組" );
            ZH( "item esp", "物品透視" );
            ZH( "item chams", "物品材質" );
            ZH( "item glow", "物品發光" );
            ZH( "primary", "主要" );
            ZH( "secondary", "次要" );
            ZH( "projectile esp", "投擲物透視" );
            ZH( "inferno esp", "燃燒區透視" );
            ZH( "max dist", "最大距離" );
            ZH( "fill color", "填充顏色" );
            ZH( "outline thickness", "外框粗細" );
            ZH( "indicator", "指示器" );
            ZH( "landing indicator", "落點指示器" );
            ZH( "arc color", "弧線顏色" );
            ZH( "bomb timer", "炸彈計時器" );
            ZH( "spectator list", "觀戰列表" );
            ZH( "skybox material", "天空盒材質" );
            ZH( "skybox", "天空盒" );
            ZH( "skybox color", "天空盒顏色" );
            ZH( "sky color", "天空顏色" );
            ZH( "cloud color", "雲層顏色" );
            ZH( "sun color", "太陽顏色" );
            ZH( "world color", "世界顏色" );
            ZH( "lighting", "光照" );
            ZH( "intensity", "亮度" );
            ZH( "gamma", "伽瑪" );

            ZH( "wear", "磨損" );
            ZH( "seed", "模板編號" );
            ZH( "search", "搜尋" );
            ZH( "search skins...", "搜尋造型..." );
            ZH( "apply", "套用" );
            ZH( "remove", "移除" );
            ZH( "back", "返回" );
            ZH( "team", "隊伍" );
            ZH( "terrorist", "恐怖份子" );
            ZH( "counter-terrorist", "反恐小組" );
            ZH( "factory new", "嶄新出廠" );
            ZH( "minimal wear", "輕微磨損" );
            ZH( "field-tested", "久經沙場" );
            ZH( "well-worn", "破損不堪" );
            ZH( "battle-scarred", "戰痕累累" );

            ZH( "hit logs", "命中記錄" );
            ZH( "console logs", "控制台記錄" );
            ZH( "chat logs", "聊天記錄" );
            ZH( "miss logs", "未命中記錄" );
            ZH( "duration", "持續時間" );
            ZH( "hit sound", "命中音效" );
            ZH( "death sound", "死亡音效" );
            ZH( "type", "類型" );
            ZH( "volume", "音量" );
            ZH( "sound", "音效" );
            ZH( "preview", "預聽" );
            ZH( "file", "檔案" );
            ZH( "hit marker", "命中標記" );
            ZH( "hit effect", "命中特效" );
            ZH( "death effect", "死亡特效" );
            ZH( "scoreboard weapons", "計分板武器" );
            ZH( "bullet impacts", "子彈落點" );
            ZH( "overlay", "覆蓋顯示" );
            ZH( "sparks", "火花" );
            ZH( "both", "兩者" );
            ZH( "edge", "邊緣" );
            ZH( "spark", "火花" );
            ZH( "bullet tracers", "子彈曳光" );
            ZH( "projectile trajectory", "投擲物軌跡" );
            ZH( "straight throw", "直線投擲" );
            ZH( "held color", "持有顏色" );
            ZH( "thrown color", "投出顏色" );
            ZH( "will damage held color", "可造成傷害（持有）" );
            ZH( "will damage thrown color", "可造成傷害（投出）" );
            ZH( "dynamic light", "動態光源" );
            ZH( "radius", "半徑" );
            ZH( "z offset", "高度偏移" );
            ZH( "penetration crosshair", "穿牆準星" );
            ZH( "can penetrate", "可穿透" );
            ZH( "can pen outline", "可穿透外框" );
            ZH( "blocked", "不可穿透" );
            ZH( "blocked outline", "不可穿透外框" );
            ZH( "bhop", "連跳" );
            ZH( "airstrafe", "空中加速" );
            ZH( "fully directional", "全方向" );
            ZH( "test strafer", "測試空中加速" );
            ZH( "jumpbug", "跳躍漏洞" );
            ZH( "edgejump", "邊緣跳" );
            ZH( "edgebug", "邊緣漏洞" );
            ZH( "edgestop", "邊緣停止" );
            ZH( "fast ladder", "快速爬梯" );
            ZH( "slowwalk", "慢走" );
            ZH( "autobuy", "自動購買" );
            ZH( "primary weapon", "主要武器" );
            ZH( "secondary weapon", "副武器" );
            ZH( "grenades", "投擲物" );
            ZH( "armor + helmet", "護甲 + 頭盔" );
            ZH( "defuse kit", "拆彈器" );
            ZH( "taser", "電擊槍" );
            ZH( "rifle", "步槍" );
            ZH( "scoped rifle", "開鏡步槍" );
            ZH( "scout", "輕狙" );
            ZH( "awp", "AWP" );
            ZH( "auto sniper", "連狙" );
            ZH( "dual elites", "雙槍" );
            ZH( "five-seven/tec-9", "Five-SeveN / Tec-9" );
            ZH( "deagle", "沙漠之鷹" );
            ZH( "revolver", "左輪" );
            ZH( "molotov", "燃燒瓶" );
            ZH( "he grenade", "高爆手榴彈" );
            ZH( "smoke", "煙霧彈" );
            ZH( "flashbang", "閃光彈" );
            ZH( "decoy", "誘餌彈" );

            ZH( "save", "儲存" );
            ZH( "reset", "重設" );
            ZH( "confirm", "確認" );
            ZH( "delete", "刪除" );
            ZH( "import", "匯入設定" );
            ZH( "export", "匯出設定" );
            ZH( "search configs...", "搜尋設定..." );
            ZH( "no configs found", "找不到設定檔" );
            ZH( "no matches", "沒有符合項目" );
            ZH( "settings", "設定" );
            ZH( "theme", "主題" );
            ZH( "search...", "搜尋..." );
            ZH( "keybinds", "按鍵綁定" );
            ZH( "waiting...", "等待按鍵..." );
            ZH( "toggle", "切換" );
            ZH( "hold on", "按住啟用" );
            ZH( "hold off", "按住停用" );
            ZH( "classic", "經典" );
            ZH( "damage", "傷害" );
            ZH( "custom", "自訂" );
            ZH( "shop click", "商店點擊" );
            ZH( "home click", "首頁點擊" );
            ZH( "bell", "鈴聲" );
            ZH( "killcard", "擊殺卡" );
            ZH( "bullet casing", "彈殼" );
            ZH( "coin pickup", "撿硬幣" );
            ZH( "item drop", "物品掉落" );
            ZH( "popcan", "汽水罐" );
            ZH( "key press", "按鍵聲" );
#undef ZH
        default:
            break;
        }
        return s;
    }
}
