<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <Version>2.0.8</Version>
    <AssemblyVersion>2.0.8.0</AssemblyVersion>
    <FileVersion>2.0.8.0</FileVersion>
    <ApplicationIcon>Assets\flowcast-logo.ico</ApplicationIcon>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AudioShare.Core\AudioShare.Core.csproj" />
    <ProjectReference Include="..\AudioShare.Windows\AudioShare.Windows.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\flowcast-logo.png" />
    <Resource Include="Assets\flowcast-logo.ico" />
    <Resource Include="Assets\tutorial-voicemeeter-banana.png" />
    <Resource Include="Assets\tutorial-discord-voice-video.png" />
  </ItemGroup>

</Project>
